# Generated by Django 3.0.1 on 2020-01-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('issuing_organization', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('finish_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('certification_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('FULL-TIME', 'FULL TIME'), ('PART-TIME', 'PART TIME'), ('SELF-EMPLOYED', 'SELF-EMPLOYED'), ('FREELANCE', 'FREELANCE')], max_length=70)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
