# Generated by Django 3.0.1 on 2020-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yoe', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='technologies',
            field=models.ManyToManyField(to='app.Technology'),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.ManyToManyField(to='app.Technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='app.Technology'),
        ),
    ]
