# Generated by Django 3.0.1 on 2020-01-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200103_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
