# Generated by Django 3.0.1 on 2020-01-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_job_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
