# Generated by Django 3.0.1 on 2020-01-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200104_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='certification',
        ),
        migrations.AddField(
            model_name='certification',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Technology'),
        ),
    ]
