# Generated by Django 3.0.1 on 2020-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200104_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='has_certification',
            field=models.BooleanField(default=False),
        ),
    ]
